"""Delete choice am_pm from ExcWrk.

Revision ID: 0cf67d67c254
Revises: 0d0a7629fd9b
Create Date: 2024-04-14 14:20:25.871428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType

from app.core.constants import AM_NOON_PM


# revision identifiers, used by Alembic.
revision: str = '0cf67d67c254'
down_revision: Union[str, None] = '0d0a7629fd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.Text(), nullable=True))
        batch_op.drop_column('am_noon_pm')

    with op.batch_alter_table('workout_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('am_noon_pm', ChoiceType(AM_NOON_PM), nullable=True))
        batch_op.add_column(sa.Column('descriptin', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_course', schema=None) as batch_op:
        batch_op.drop_column('descriptin')
        batch_op.drop_column('am_noon_pm')

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('am_noon_pm', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('sequence_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('descriptin')

    # ### end Alembic commands ###
