"""Many-many course-workout.

Revision ID: 0d0a7629fd9b
Revises: d12726d58fe6
Create Date: 2024-04-14 14:15:29.017752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType

from app.core.constants import AM_NOON_PM


# revision identifiers, used by Alembic.
revision: str = '0d0a7629fd9b'
down_revision: Union[str, None] = 'd12726d58fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_course',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('course_day', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_id'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='workout_id' ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('descriptin',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint('workout_id', type_='foreignkey')
        batch_op.drop_column('corse_day')
        batch_op.drop_column('am_noon_pm')
        batch_op.drop_column('workout_id')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('descriptin',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('am_noon_pm', ChoiceType(AM_NOON_PM), nullable=True))
        batch_op.drop_column('extra_data')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('descriptin',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('descriptin',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_data', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('am_noon_pm')
        batch_op.drop_column('sequence_number')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('descriptin',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('am_noon_pm', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('corse_day', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('workout_id', 'workout', ['workout_id'], ['id'])
        batch_op.alter_column('descriptin',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('workout_course')
    # ### end Alembic commands ###
