"""Gender

Revision ID: 156d3ec943d8
Revises: 9d085722b0ed
Create Date: 2024-04-08 01:20:19.473322

"""
from typing import Sequence, Union
from sqlalchemy_utils.types.choice import ChoiceType
from alembic import op
import sqlalchemy as sa
from app.core.constants import GENDER


# revision identifiers, used by Alembic.
revision: str = '156d3ec943d8'
down_revision: Union[str, None] = '9d085722b0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', ChoiceType(GENDER), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
