"""Add-table-exercise

Revision ID: 15c3f2abf6a7
Revises: ffdd1d3820b3
Create Date: 2024-04-09 21:59:27.353704

"""
from typing import Sequence, Union
from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import FileType
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType

from app.core.constants import WORKOUT_TYPE

# revision identifiers, used by Alembic.
revision: str = '15c3f2abf6a7'
down_revision: Union[str, None] = 'ffdd1d3820b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('descriptin', sa.Text(), nullable=False),
    sa.Column('video', FileType(storage = FileSystemStorage(path="./upload")), nullable=True),
    sa.Column('workout_type', ChoiceType(WORKOUT_TYPE), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.alter_column('sleep_duration',
               existing_type=sa.DATETIME(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.alter_column('sleep_duration',
               existing_type=sa.Float(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    op.drop_table('exercise')
    # ### end Alembic commands ###
