"""add purpose in User

Revision ID: 233e2a4f498d
Revises: c464c4d263c4
Create Date: 2024-04-15 21:07:23.737753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy_utils.types.choice import ChoiceType
from app.core.constants import ACTIVITY_PURPOSE


# revision identifiers, used by Alembic.
revision: str = '233e2a4f498d'
down_revision: Union[str, None] = 'c464c4d263c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', ChoiceType(ACTIVITY_PURPOSE), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
