"""fix: Change user fields.

Revision ID: 2396728d9816
Revises: 634b7fd3a5cc
Create Date: 2024-04-16 12:40:07.101662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType
from app.core.constants import PHYSICAL_ACTIVITY, ACTIVITY_PURPOSE

# revision identifiers, used by Alembic.
revision: str = '2396728d9816'
down_revision: Union[str, None] = '634b7fd3a5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', ChoiceType(ACTIVITY_PURPOSE), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', ChoiceType(ACTIVITY_PURPOSE), nullable=True))
        batch_op.drop_column('activity')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', ChoiceType(ACTIVITY_PURPOSE), nullable=True))
        batch_op.alter_column('telegram_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('purpose')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('purpose')

    with op.batch_alter_table('calorie', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
