"""Change schedule fields and others.

Revision ID: 453af9249583
Revises: 2396728d9816
Create Date: 2024-04-18 20:50:54.690375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453af9249583'
down_revision: Union[str, None] = '2396728d9816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exerciseworkout')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('workout_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('descriptin')

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('descriptin')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('descriptin')

    op.create_table('exerciseworkout',
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.Column('workout_id', sa.INTEGER(), nullable=True),
    sa.Column('sequence_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
