"""All remainder=true.

Revision ID: 5771c00fce6d
Revises: 8a43f3b281b0
Create Date: 2024-04-15 14:49:28.875701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5771c00fce6d'
down_revision: Union[str, None] = '8a43f3b281b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('possibleanswer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('possibleanswer',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('possibleanswer_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['possibleanswer_id'], ['possibleanswer.id'], name='possibleanswer_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
