"""Change field name description.

Revision ID: 634b7fd3a5cc
Revises: c464c4d263c4
Create Date: 2024-04-15 18:18:38.808493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634b7fd3a5cc'
down_revision: Union[str, None] ='c464c4d263c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('descriptin')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('descriptin')

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('descriptin')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('descriptin')

    with op.batch_alter_table('workout_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('descriptin')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('exercise_workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptin', sa.TEXT(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
