"""Add stop_reminder_adv and table Advertisement.

Revision ID: 6642ff71df04
Revises: d96b9ff8107b
Create Date: 2024-06-27 16:21:54.850148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import FileType
from sqlalchemy_utils.types.choice import ChoiceType

from app.core.constants import GENDER_OR_NONE
from app.core.config import STATIC_DIR



# revision identifiers, used by Alembic.
revision: str = '6642ff71df04'
down_revision: Union[str, None] = 'd96b9ff8107b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('image', FileType(storage = FileSystemStorage(path=STATIC_DIR)), nullable=True),
    sa.Column('hour_to_adv', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('gender', ChoiceType(GENDER_OR_NONE), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(8<hour_to_adv) and (hour_to_adv<21)', name='check_min_max_hour'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hour_to_adv', 'active', name='unique_hour_and_active'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_reminder_adv', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('stop_reminder_adv')

    op.drop_table('advertisement')
    # ### end Alembic commands ###
