"""Chande workouts tables

Revision ID: 76aa57ba6258
Revises: 2396728d9816
Create Date: 2024-04-18 18:46:28.832060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.core.constants import ACTIVITY_PURPOSE, GENDER, WORKOUT_TYPE


# revision identifiers, used by Alembic.
revision: str = '76aa57ba6258'
down_revision: Union[str, None] = '2396728d9816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutexercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('workout_course')
    op.drop_table('exercise_workout')
    op.drop_table('course')
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sqlalchemy_utils.types.choice.ChoiceType(WORKOUT_TYPE), nullable=False))
        batch_op.add_column(sa.Column('gender', sqlalchemy_utils.types.choice.ChoiceType(GENDER), nullable=False))
        batch_op.add_column(sa.Column('purpose', sqlalchemy_utils.types.choice.ChoiceType(ACTIVITY_PURPOSE), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('workout_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('purpose')
        batch_op.drop_column('gender')
        batch_op.drop_column('group')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('course',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise_workout',
    sa.Column('exercise_id', sa.INTEGER(), nullable=True),
    sa.Column('workout_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sequence_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='exercise_id'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_course',
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('workout_id', sa.INTEGER(), nullable=True),
    sa.Column('course_day', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('am_noon_pm', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_id'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], name='workout_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('workoutexercise')
    # ### end Alembic commands ###
