"""Delete shedule, add schedule.

Revision ID: 8a43f3b281b0
Revises: 0cf67d67c254
Create Date: 2024-04-15 12:18:42.463171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a43f3b281b0'
down_revision: Union[str, None] = '0cf67d67c254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_course', sa.DateTime(), nullable=True),
    sa.Column('stop_reminder_train', sa.Boolean(), nullable=True),
    sa.Column('stop_reminder_sleep', sa.Boolean(), nullable=True),
    sa.Column('stop_reminder_calories', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shedule',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('start_course', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('schedule')
    # ### end Alembic commands ###
