"""Add fields user, file, new tables in questionaire.

Revision ID: 9f3f6831128a
Revises: 156d3ec943d8
Create Date: 2024-04-08 12:23:11.932316

"""
from typing import Sequence, Union
from sqlalchemy_utils.types.choice import ChoiceType

from alembic import op
import sqlalchemy as sa

from app.core.constants import ACTIVITY_PURPOSE, WORKOUT_TYPE

# revision identifiers, used by Alembic.
revision: str = '9f3f6831128a'
down_revision: Union[str, None] = '156d3ec943d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', ChoiceType(WORKOUT_TYPE), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('activity', ChoiceType(ACTIVITY_PURPOSE), nullable=True))
        batch_op.create_unique_constraint('telegram_id', ['telegram_id'])
        batch_op.create_unique_constraint('name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activity')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')
        batch_op.drop_column('name')
        batch_op.drop_column('telegram_id')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('workout_type')

    # ### end Alembic commands ###
