"""Correct User model

Revision ID: cece0886f5f1
Revises: c464c4d263c4
Create Date: 2024-04-17 10:17:26.840450

"""
from typing import Sequence, Union

import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

from app.core.constants import ACTIVITY_PURPOSE

# revision identifiers, used by Alembic.
revision: str = 'cece0886f5f1'
down_revision: Union[str, None] = 'c464c4d263c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sqlalchemy_utils.types.choice.ChoiceType(ACTIVITY_PURPOSE)))
        batch_op.alter_column('telegram_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
