"""Location in user and utc_offset in schedule

Revision ID: d96b9ff8107b
Revises: fb35598b2204
Create Date: 2024-06-25 18:21:50.321234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96b9ff8107b'
down_revision: Union[str, None] = 'fb35598b2204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utc_offset', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('utc_offset')

    # ### end Alembic commands ###
