"""Add new tables in questionaire.

Revision ID: e5f22b24e494
Revises: 9f3f6831128a
Create Date: 2024-04-08 14:51:00.468150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f22b24e494'
down_revision: Union[str, None] = '9f3f6831128a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('possibleanswer',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('possibleanswer_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['possibleanswer_id'], ['possibleanswer.id'], name='fk_question_possible_answer_id_possible_answer'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('possibleanswer')
    # ### end Alembic commands ###
