"""New calorie string

Revision ID: f4abf933a5ac
Revises: 233e2a4f498d
Create Date: 2024-04-17 11:50:53.517504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils.types.choice import ChoiceType
from app.core.constants import ACTIVITY_PURPOSE


# revision identifiers, used by Alembic.
revision: str = 'f4abf933a5ac'
down_revision: Union[str, None] = '233e2a4f498d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', ChoiceType(ACTIVITY_PURPOSE), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
