"""Add sequence_number

Revision ID: fb35598b2204
Revises: 76aa57ba6258
Create Date: 2024-04-25 18:47:22.892707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb35598b2204'
down_revision: Union[str, None] = '76aa57ba6258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.drop_column('sequence_number')

    # ### end Alembic commands ###
