"""Add table sleep

Revision ID: ffdd1d3820b3
Revises: e5f22b24e494
Create Date: 2024-04-08 23:54:27.490254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdd1d3820b3'
down_revision: Union[str, None] = 'e5f22b24e494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('go_to_bed_time', sa.DateTime(), nullable=True),
    sa.Column('wake_up_time', sa.DateTime(), nullable=True),
    sa.Column('sleep_duration', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep')
    # ### end Alembic commands ###
